### ISSUE TITLE
Skipping repeat notes?

### ISSUE THREAD

**Issue by TJesionowski** [captnfab/PianoBooster#294] opened 2021-04-10 00:46 UTC
Steps to reproduce:

1. Download MIDI file from https://bitmidi.com/uploads/86046.mid
2. Open PianoBooster, load downloaded file
3. Do MIDI setup if required
4. Select the "Listen" option under "Skill".
5. Press space to start playing the song. The 2nd E note fails to play, instead the first E note is continued until the F# note.

When I mess around with the "Hands" option I can sometimes get it to stutter when the 2nd E note comes up rather than ignoring it completely. This behavior has happened on both right and left hand mode.

There are other audible omissions in the song, but the 2nd E note fails every time.

PS: I moved on to the intro lesson and discovered that keys get "stuck" when pressed if and only if they're the key I'm supposed to press. I opened the intro lesson, set it to Follow You, pressed the first C note, then that key stopped responding. I thought my piano might be broken so I transposed it to a different note, got that note in, then could press C all I wanted but not the new note.

**Comment by louis-barman** [comment] 2021-04-10 21:37
Unfortunately I cannot reproduce your problem. See the recording I made from pianobooster using fluidsynth as the the sound generator 
[pianobooster-86046.zip](https://github.com/pianobooster/PianoBooster/files/6290786/pianobooster-86046.zip)

I would need more info to try and work out what is going on. So please answer the following questions:

1. What version of pianobooster are you using?
2. What OS are you using (eg Windows or Mac)
3. What midi output are you using?
4. What is the make and model number of your piano keyboard that you are using?

To try and narrow down the problem please can you retest using the internal fluidsynth midi output as the sound generator.

I don't have enough info to try and find the issue that you raised in your PS: A video recording of the problem might help. Again please ensure that you retest using the internal fluidsynth sound generator.

**Comment by louis-barman** [comment] 2021-05-11 19:51
Closing as unable to reproduce and no reply to my questions.

**Closed as completed by louis-barman** 2021-05-11 19:51 UTC
